### ISSUE TITLE
If subclass from ARSPopover and trying to popup in application it is presenting entire view. Note: Creating instance using init(nibName: bundle)

### ISSUE THREAD

**Issue by abhikpo** [soberman/ARSPopover#1]

**Comment by soberman** [comment]
I am not sure you should subclass it, there is not point to do so. Just use it as is, you have all the properties you need to customize it and even block method to add your content to it.

**Comment by abhikpo** [comment]
It is my mistake. I didn't set properties properly. It is working. Thank you.

**Comment by soberman** [comment]
No problems. I close the issue.
