### ISSUE TITLE
Q: how to change popover size when it's displayed?

### ISSUE THREAD

**Issue by 4ntoine** [soberman/ARSPopover#10]
I need to change popover size when it's shown. I know i can dismiss it without animation and show new one without animation but it leads to flickering and it looks bad.

Any idea on how to do it?

**Comment by soberman** [comment]
You forgot about the `contentSize` property. Simply `popoverController.contentSize = CGSizeMake(100, 50);`.
You can open the demo project, that comes with the source files in case you make a clone, and see how I configure popovers in ViewController.m class.

**Comment by 4ntoine** [comment]
Hey! I've seen it but i did not see setter is overriden to apply the size immediately. I will try it, thanks

**Comment by 4ntoine** [comment]
No, it does not work. It sets content size only, but popover size remains the same.
Here is the solution (from http://stackoverflow.com/questions/8516736/how-to-dynamically-change-the-contentsize-of-uipopovercontroller):

```
popoverController.contentSize = contentSize;
popoverController.preferredContentSize = contentSize;

insertedView.frame = ... // adjust inserted view frame too
```
