### ISSUE TITLE
Dismissing Popover with cancel Button or OnSelectedDay

### ISSUE THREAD

**Issue by levisbotio** [soberman/ARSPopover#3]
Hi! I'm having trouble dismissing it using those method. I tried to add tag on popoverController and inside the .insertContentIntoPopover and tried `view.viewWithTag(calendar_tag)?.removeFromSuperview()` But it seems to be not working. Thanks!

**Comment by soberman** [comment]
Hey. You have `- (void)closePopover;` method to use, provided to you by the popover, which you just call on tap in your button. This method will close popup.

**Comment by levisbotio** [comment]
Thanks very much! ;)

**Comment by soberman** [comment]
No problems, I close an issue.
