### ISSUE TITLE
Bug showing popover for the second time.

### ISSUE THREAD

**Issue by levisbotio** [soberman/ARSPopover#4]
When i'm setting the variable inside the class like this:
![screen shot 2015-10-05 at 6 29 13 am](https://cloud.githubusercontent.com/assets/14213430/10279330/76e6d4f6-6b2a-11e5-9ec8-48f9083b364b.png)
But if I'm setting it inside the `showDatePickerPopover()` It's working fine. But the problem if i do that I can't call the `closePopover()` method inside any function. Here's the video:
https://www.youtube.com/watch?v=5AGi-6cw8gw
Thanks!

**Comment by soberman** [comment]
Just create another `UIBarButtonItem` with action of `closePopover()` and assign it to your button from your controller, that you instantiate from storyboard. This should be sufficient.

**Comment by levisbotio** [comment]
Thanks again! ;)
