### ISSUE TITLE
Layout issue when presenting on iPhone 6 Plus in landscape 

### ISSUE THREAD

**Issue by massimobio** [soberman/ARSPopover#6]
If I try to present the popover form a button in landscape on iPhone 6 Plus I get a UIModalPresentationFormSheet instead of a popover and the content is not loaded.
The issue is reproducible with the demo app if you enable landscape orientation and fix the autolayout constrains of the two buttons.
Presenting in landscape on iPhone 6 and lower works.

**Comment by massimobio** [comment]
Found a solution to this here:
http://stackoverflow.com/questions/30378249/uimodalpresentationpopover-for-iphone-6-plus-in-landscape-doesnt-display-popove/30481565#30481565

Sorry for not making pull request but the above solution requires iOS 8.3 so I'm not sure how you handle that with the current 8.0 requirement you have.

**Comment by soberman** [comment]
Yes, thank you for finding this bug and the solution as well. I have just merged a PR that handles this issue. You may get the latest version here or from CocoaPods in couple hours.  
Thanks again! 👍
